extends:
  - eslint:recommended
parserOptions:
  ecmaVersion: 2021
  sourceType: module
env:
  node: true
  es6: true
rules:
  no-unused-vars:
    - error
    - ignoreRestSiblings: true
      argsIgnorePattern: ^_
